export const STANDARD_ACCOUNT_NAMES: Record<string, string> = {
    // 1. DÖNEN VARLIKLAR
    '100': 'Kasa',
    '101': 'Alınan Çekler',
    '102': 'Bankalar',
    '103': 'Verilen Çekler ve Ödeme Emirleri (-)',
    '108': 'Diğer Hazır Değerler',
    '110': 'Hisse Senetleri',
    '111': 'Özel Kesim Tahvil, Senet ve Bonoları',
    '112': 'Kamu Kesimi Tahvil, Senet ve Bonoları',
    '118': 'Diğer Menkul Kıymetler',
    '119': 'Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)',
    '120': 'Alıcılar',
    '121': 'Alacak Senetleri',
    '122': 'Alacak Senetleri Reeskontu (-)',
    '124': 'Kazanılmamış Finansal Kiralama Faiz Gelirleri (-)',
    '126': 'Verilen Depozito ve Teminatlar',
    '127': 'Diğer Ticari Alacaklar',
    '128': 'Şüpheli Ticari Alacaklar',
    '129': 'Şüpheli Ticari Alacaklar Karşılığı (-)',
    '131': 'Ortaklardan Alacaklar',
    '132': 'İştiraklerden Alacaklar',
    '133': 'Bağlı Ortaklıklardan Alacaklar',
    '135': 'Personelden Alacaklar',
    '136': 'Diğer Çeşitli Alacaklar',
    '137': 'Diğer Alacak Senetleri Reeskontu (-)',
    '138': 'Şüpheli Diğer Alacaklar',
    '139': 'Şüpheli Diğer Alacaklar Karşılığı (-)',
    '150': 'İlk Madde ve Malzeme',
    '151': 'Yarı Mamuller - Üretim',
    '152': 'Mamuller',
    '153': 'Ticari Mallar',
    '157': 'Diğer Stoklar',
    '158': 'Stok Değer Düşüklüğü Karşılığı (-)',
    '159': 'Verilen Sipariş Avansları',
    '170': 'Yıllara Yaygın İnşaat ve Onarım Maliyetleri',
    '179': 'Taşeronlara Verilen Avanslar',
    '180': 'Gelecek Aylara Ait Giderler',
    '181': 'Gelir Tahakkukları',
    '190': 'Devreden KDV',
    '191': 'İndirilecek KDV',
    '192': 'Diğer KDV',
    '193': 'Peşin Ödenen Vergiler ve Fonlar',
    '195': 'İş Avansları',
    '196': 'Personel Avansları',
    '197': 'Sayım ve Tesellüm Noksanları',
    '198': 'Diğer Çeşitli Dönen Varlıklar',
    '199': 'Diğer Dönen Varlıklar Karşılığı (-)',

    // 2. DURAN VARLIKLAR
    '220': 'Alıcılar',
    '221': 'Alacak Senetleri',
    '222': 'Alacak Senetleri Reeskontu (-)',
    '224': 'Kazanılmamış Finansal Kiralama Faiz Gelirleri (-)',
    '226': 'Verilen Depozito ve Teminatlar',
    '229': 'Şüpheli Ticari Alacaklar Karşılığı (-)',
    '230': 'Ortaklardan Alacaklar',
    '231': 'İştiraklerden Alacaklar',
    '232': 'Bağlı Ortaklıklardan Alacaklar',
    '236': 'Diğer Çeşitli Alacaklar',
    '237': 'Diğer Alacak Senetleri Reeskontu (-)',
    '239': 'Şüpheli Diğer Alacaklar Karşılığı (-)',
    '240': 'Bağlı Menkul Kıymetler',
    '241': 'İştirakler',
    '242': 'Bağlı Ortaklıklar',
    '243': 'İştiraklere Sermaye Taahhütleri (-)',
    '244': 'Bağlı Ortaklıklara Sermaye Taahhütleri (-)',
    '245': 'Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)',
    '248': 'Diğer Mali Duran Varlıklar',
    '249': 'Diğer Mali Duran Varlıklar Karşılığı (-)',
    '250': 'Arazi ve Arsalar',
    '251': 'Yeraltı ve Yerüstü Düzenleri',
    '252': 'Binalar',
    '253': 'Tesis, Makine ve Cihazlar',
    '254': 'Taşıtlar',
    '255': 'Demirbaşlar',
    '256': 'Diğer Maddi Duran Varlıklar',
    '257': 'Birikmiş Amortismanlar (-)',
    '258': 'Yapılmakta Olan Yatırımlar',
    '259': 'Verilen Avanslar',
    '260': 'Haklar',
    '261': 'Şerefiye',
    '262': 'Kuruluş ve Örgütlenme Giderleri',
    '263': 'Araştırma ve Geliştirme Giderleri',
    '264': 'Özel Maliyetler',
    '267': 'Diğer Maddi Olmayan Duran Varlıklar',
    '268': 'Birikmiş Amortismanlar (-)',
    '269': 'Verilen Sipariş Avansları',
    '271': 'Arama Giderleri',
    '272': 'Hazırlık ve Geliştirme Giderleri',
    '277': 'Diğer Özel Tükenmeye Tabi Varlıklar',
    '278': 'Birikmiş Tükenme Payları (-)',
    '279': 'Verilen Avanslar',
    '280': 'Gelecek Yıllara Ait Giderler',
    '281': 'Gelir Tahakkukları',
    '291': 'Gelecek Yıllar İhtiyacı Stoklar',
    '292': 'Diğer KDV',
    '293': 'Gelecek Yıllar Peşin Ödenen Vergiler ve Fonlar',
    '294': 'Elden Çıkarılacak Stoklar ve Maddi Duran Varlıklar',
    '295': 'Peşin Ödenen Vergiler ve Fonlar',
    '297': 'Diğer Çeşitli Duran Varlıklar',
    '298': 'Stok Değer Düşüklüğü Karşılığı (-)',
    '299': 'Birikmiş Amortismanlar (-)',

    // 3. KISA VADELİ YABANCI KAYNAKLAR
    '300': 'Banka Kredileri',
    '303': 'Uzun Vadeli Kredilerin Anapara Taksitleri ve Faizleri',
    '304': 'Tahvil Anapara Borç, Taksit ve Faizleri',
    '305': 'Çıkarılmış Bonolar ve Senetler',
    '306': 'Çıkarılmış Diğer Menkul Kıymetler',
    '308': 'Menkul Kıymetler İhraç Farkları (-)',
    '309': 'Diğer Mali Borçlar',
    '320': 'Satıcılar',
    '321': 'Borç Senetleri',
    '322': 'Borç Senetleri Reeskontu (-)',
    '326': 'Alınan Depozito ve Teminatlar',
    '329': 'Diğer Ticari Borçlar',
    '331': 'Ortaklara Borçlar',
    '332': 'İştiraklere Borçlar',
    '333': 'Bağlı Ortaklıklara Borçlar',
    '335': 'Personele Borçlar',
    '336': 'Diğer Çeşitli Borçlar',
    '337': 'Diğer Borç Senetleri Reeskontu (-)',
    '340': 'Alınan Sipariş Avansları',
    '349': 'Alınan Diğer Avanslar',
    '350': 'Yıllara Yaygın İnşaat ve Onarım Hakedişleri',
    '358': 'Yıllara Yaygın İnşaat Enflasyon Düzeltme Hesabı',
    '360': 'Ödenecek Vergi ve Fonlar',
    '361': 'Ödenecek Sosyal Güvenlik Kesintileri',
    '368': 'Vadesi Geçmiş Ertelenmiş veya Taksitlendirilmiş Vergi ve Diğer Yükümlülükler',
    '369': 'Ödenmesi Gereken Diğer Yükümlülükler',
    '370': 'Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları',
    '371': 'Dönem Karının Peşin Ödenen Vergi ve Diğer Yükümlülükleri (-)',
    '372': 'Kıdem Tazminatı Karşılığı',
    '373': 'Maliyet Giderleri Karşılığı',
    '379': 'Diğer Borç ve Gider Karşılıkları',
    '380': 'Gelecek Aylara Ait Gelirler',
    '381': 'Gider Tahakkukları',
    '391': 'Hesaplanan KDV',
    '392': 'Diğer KDV',
    '393': 'Merkez ve Şubeler Cari Hesabı',
    '397': 'Sayım ve Tesellüm Fazlaları',
    '398': 'Enflasyon Düzeltmesi Hesabı',
    '399': 'Diğer Çeşitli Kısa Vadeli Yabancı Kaynaklar',

    // 4. UZUN VADELİ YABANCI KAYNAKLAR
    '400': 'Banka Kredileri',
    '405': 'Çıkarılmış Tahviller',
    '407': 'Çıkarılmış Diğer Menkul Kıymetler',
    '408': 'Menkul Kıymetler İhraç Farkı (-)',
    '409': 'Diğer Mali Borçlar',
    '420': 'Satıcılar',
    '421': 'Borç Senetleri',
    '422': 'Borç Senetleri Reeskontu (-)',
    '426': 'Alınan Depozito ve Teminatlar',
    '429': 'Diğer Ticari Borçlar',
    '431': 'Ortaklara Borçlar',
    '432': 'İştiraklere Borçlar',
    '433': 'Bağlı Ortaklıklara Borçlar',
    '436': 'Diğer Çeşitli Borçlar',
    '437': 'Diğer Borç Senetleri Reeskontu (-)',
    '438': 'Kamuyu Olan Ertelenmiş veya Taksitlendirilmiş Borçlar',
    '440': 'Alınan Sipariş Avansları',
    '449': 'Alınan Diğer Avanslar',
    '472': 'Kıdem Tazminatı Karşılığı',
    '479': 'Diğer Borç ve Gider Karşılıkları',
    '480': 'Gelecek Yıllara Ait Gelirler',
    '481': 'Gider Tahakkukları',
    '492': 'Gelecek Yıllara Ertelenen veya Terkin Edilecek KDV',
    '493': 'Tesis Katılım Payları',
    '499': 'Diğer Çeşitli Uzun Vadeli Yabancı Kaynaklar',

    // 5. ÖZ KAYNAKLAR
    '500': 'Sermaye',
    '501': 'Ödenmemiş Sermaye (-)',
    '502': 'Sermaye Düzeltmesi Olumlu Farkları',
    '503': 'Sermaye Düzeltmesi Olumsuz Farkları (-)',
    '520': 'Hisse Senedi İhraç Primleri',
    '521': 'Hisse Senedi İptal Karları',
    '522': 'Maddi Duran Varlık Yeniden Değerleme Artışları',
    '523': 'İştirakler Yeniden Değerleme Artışları',
    '529': 'Diğer Sermaye Yedekleri',
    '540': 'Yasal Yedekler',
    '541': 'Statü Yedekleri',
    '542': 'Olağanüstü Yedekler',
    '548': 'Diğer Kar Yedekleri',
    '549': 'Özel Fonlar',
    '570': 'Geçmiş Yıllar Karları',
    '580': 'Geçmiş Yıllar Zararları (-)',
    '590': 'Dönem Net Karı',
    '591': 'Dönem Net Zararı (-)',

    // 6. GELİR TABLOSU HESAPLARI
    '600': 'Yurt İçi Satışlar',
    '601': 'Yurt Dışı Satışlar',
    '602': 'Diğer Gelirler',
    '610': 'Satıştan İadeler (-)',
    '611': 'Satış İskontoları (-)',
    '612': 'Diğer İndirimler (-)',
    '620': 'Satılan Mamuller Maliyeti (-)',
    '621': 'Satılan Ticari Mallar Maliyeti (-)',
    '622': 'Satılan Hizmet Maliyeti (-)',
    '623': 'Diğer Satışların Maliyeti (-)',
    '630': 'Araştırma ve Geliştirme Giderleri (-)',
    '631': 'Pazarlama, Satış ve Dağıtım Giderleri (-)',
    '632': 'Genel Yönetim Giderleri (-)',
    '640': 'İştiraklerden Temettü Gelirleri',
    '641': 'Bağlı Ortaklıklardan Temettü Gelirleri',
    '642': 'Faiz Gelirleri',
    '643': 'Komisyon Gelirleri',
    '644': 'Konusu Kalmayan Karşılıklar',
    '645': 'Menkul Kıymet Satış Karları',
    '646': 'Kambiyo Karları',
    '647': 'Reeskont Faiz Gelirleri',
    '648': 'Enflasyon Düzeltmesi Karları',
    '649': 'Diğer Olağan Gelir ve Karlar',
    '653': 'Komisyon Giderleri (-)',
    '654': 'Karşılık Giderleri (-)',
    '655': 'Menkul Kıymet Satış Zararları (-)',
    '656': 'Kambiyo Zararları (-)',
    '657': 'Reeskont Faiz Giderleri (-)',
    '658': 'Enflasyon Düzeltmesi Zararları (-)',
    '659': 'Diğer Olağan Gider ve Zararlar (-)',
    '660': 'Kısa Vadeli Borçlanma Giderleri (-)',
    '661': 'Uzun Vadeli Borçlanma Giderleri (-)',
    '671': 'Önceki Dönem Gelir ve Karları',
    '679': 'Diğer Olağandışı Gelir ve Karlar',
    '680': 'Çalışmayan Kısım Gider ve Zararları (-)',
    '681': 'Önceki Dönem Gider ve Zararları (-)',
    '689': 'Diğer Olağandışı Gider ve Zararlar (-)',
    '690': 'Dönem Karı veya Zararı',
    '691': 'Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları (-)',
    '692': 'Dönem Net Karı veya Zararı',
    '697': 'Yıllara Yaygın İnşaat Enflasyon Düzeltme Hesabı',
    '698': 'Enflasyon Düzeltme Hesabı',

    // 7. MALİYET HESAPLARI
    '710': 'Direkt İlk Madde ve Malzeme Giderleri',
    '711': 'Direkt İlk Madde ve Malzeme Giderleri Yansıtma Hesabı',
    '720': 'Direkt İşçilik Giderleri',
    '721': 'Direkt İşçilik Giderleri Yansıtma Hesabı',
    '730': 'Genel Üretim Giderleri',
    '731': 'Genel Üretim Giderleri Yansıtma Hesabı',
    '740': 'Hizmet Üretim Maliyeti',
    '741': 'Hizmet Üretim Maliyeti Yansıtma Hesabı',
    '750': 'Araştırma ve Geliştirme Giderleri',
    '751': 'Araştırma ve Geliştirme Giderleri Yansıtma Hesabı',
    '760': 'Pazarlama Satış ve Dağıtım Giderleri',
    '761': 'Pazarlama Satış ve Dağıtım Giderleri Yansıtma Hesabı',
    '770': 'Genel Yönetim Giderleri',
    '771': 'Genel Yönetim Giderleri Yansıtma Hesabı',
    '780': 'Finansman Giderleri',
    '781': 'Finansman Giderleri Yansıtma Hesabı',

    // 7B
    '790': 'İlk Madde ve Malzeme Giderleri',
    '791': 'İşçi Ücret ve Giderleri',
    '792': 'Memur Ücret ve Giderleri',
    '793': 'Dışarıdan Sağlanan Fayda ve Hizmetler',
    '794': 'Çeşitli Giderler',
    '795': 'Vergi, Resim ve Harçlar',
    '796': 'Amortismanlar ve Tükenme Payları',
    '797': 'Finansman Giderleri',
    '798': 'Gider Çeşitleri Yansıtma Hesapları',
    '799': 'Üretim Maliyet Hesabı',
};
